@props(['surface'])
<header class='dashboard-topbar'>
 <div class='topbar-start'><button class='icon-button mobile-menu-button' type='button' data-sidebar-open aria-controls='dashboard-sidebar' aria-expanded='false' aria-label='Buka navigasi'>☰</button><button class='icon-button desktop-menu-button' type='button' data-sidebar-collapse aria-label='Ubah ukuran sidebar'>☰</button><div class='topbar-search'><span>⌕</span><input type='search' placeholder='Cari menu…' aria-label='Cari menu'></div></div>
 <div class='topbar-actions'>
  <button class='icon-button' type='button' data-theme-toggle aria-label='Ubah tema'>◐</button>
  <div class='dropdown'><button class='icon-button notification-trigger' data-bs-toggle='dropdown' aria-expanded='false' aria-label='Notifikasi'>♢@if(auth()->user()->notifications()->whereNull('read_at')->exists())<span class='notification-indicator'></span>@endif</button><div class='dropdown-menu dropdown-menu-end notification-menu'><div class='dropdown-heading'><strong>Notifikasi</strong><span>{{ auth()->user()->notifications()->whereNull('read_at')->count() }} baru</span></div>@forelse(auth()->user()->notifications()->latest()->limit(4)->get() as $notification)<x-notification-item :notification='$notification' />@empty<x-empty-state title='Belum ada notifikasi' description='Pembaruan penting akan muncul di sini.' compact />@endforelse</div></div>
  <div class='dropdown'><button class='profile-trigger' data-bs-toggle='dropdown' aria-expanded='false'><span class='profile-avatar'>{{ str(auth()->user()->name)->substr(0,1)->upper() }}</span><span class='profile-copy'><strong>{{ auth()->user()->name }}</strong><small>{{ str($surface)->headline() }}</small></span><span>⌄</span></button><div class='dropdown-menu dropdown-menu-end profile-menu'><div class='px-3 py-2'><strong>{{ auth()->user()->name }}</strong><small class='d-block text-muted'>{{ auth()->user()->email }}</small></div><div class='dropdown-divider'></div><a class='dropdown-item' href='{{ route('surfaces.select') }}'>Ganti surface</a><form method='POST' action='{{ route('logout') }}'>@csrf<button class='dropdown-item text-danger'>Keluar</button></form></div></div>
 </div>
</header>
