@extends('layouts.mitra')
@section('title',$accommodation->name) @section('page-title',$accommodation->name) @section('page-description','Kelola properti, tipe kamar, harga, fasilitas, media, dan kalender.')
@section('content')
<div class='d-flex gap-2 mb-3'><x-status-badge :status='$accommodation->status' /><a class='btn btn-sm btn-outline-lokantara' href='{{ route('mitra.accommodation.edit',$accommodation) }}'>Edit properti</a>@if(in_array($accommodation->status,['draft','rejected']))<form method='POST' action='{{ route('mitra.accommodation.submit',$accommodation) }}'>@csrf<button class='btn btn-sm btn-lokantara'>Ajukan moderasi</button></form>@endif @if(in_array($accommodation->status,['draft','rejected','published']))<form method='POST' action='{{ route('mitra.accommodation.archive',$accommodation) }}'>@csrf<button class='btn btn-sm btn-outline-danger'>Arsipkan</button></form>@endif</div>
<div class='row g-3'><div class='col-lg-7'><x-content-card title='Preview properti'><h2>{{ $accommodation->name }}</h2><p>{{ $accommodation->description ?: 'Deskripsi belum diisi.' }}</p><p>{{ $accommodation->address }}</p><div class='tag-row'>@foreach($accommodation->facilities as $facility)<span>{{ $facility->name }}</span>@endforeach</div></x-content-card></div><div class='col-lg-5'><x-content-card title='Media properti'><form method='POST' enctype='multipart/form-data' action='{{ route('mitra.accommodation.media',$accommodation) }}'>@csrf<input class='form-control mb-2' type='file' name='image' accept='image/jpeg,image/png,image/webp' required><select class='form-select mb-2' name='role'><option value='cover'>Cover</option><option value='gallery'>Galeri</option></select><button class='btn btn-sm btn-lokantara'>Unggah</button></form><p class='mt-3'>{{ $accommodation->media->count() }} media.</p></x-content-card></div></div>
<x-content-card title='Tambah kamar' class='mt-3'><form method='POST' action='{{ route('mitra.accommodation.rooms.store',$accommodation) }}'>@csrf<div class='row'><div class='col-md-4'><x-form-input name='name' label='Nama kamar' required /></div><div class='col-md-4'><x-form-input name='room_type' label='Tipe kamar' required /></div><div class='col-md-4'><x-select name='kind' label='Jenis' required><option value='room'>Kamar</option><option value='tent_plot'>Lahan tenda</option></x-select></div></div><div class='row'><div class='col-md-2'><x-form-input name='capacity_adults' type='number' label='Dewasa' value='2' required /></div><div class='col-md-2'><x-form-input name='capacity_children' type='number' label='Anak' value='0' required /></div><div class='col-md-2'><x-form-input name='total_units' type='number' label='Total unit' value='1' required /></div><div class='col-md-3'><x-form-input name='nightly_price' type='number' label='Harga/malam' required /></div><div class='col-md-3'><x-select name='status' label='Status' required><option value='draft'>Draft</option><option value='active'>Aktif</option></x-select></div></div><button class='btn btn-lokantara'>Tambah kamar</button></form></x-content-card>
<x-table-wrapper title='Daftar kamar' class='mt-3'>@if($accommodation->accommodation->rooms->isEmpty())<tbody><tr><td><x-empty-state title='Belum ada kamar' description='Tambahkan minimal satu kamar aktif sebelum submit.' compact /></td></tr></tbody>@else<thead><tr><th>Kamar</th><th>Kapasitas</th><th>Harga</th><th>Unit</th><th>Status</th><th></th></tr></thead><tbody>@foreach($accommodation->accommodation->rooms as $room)<tr><td>{{ $room->name }}</td><td>{{ $room->capacity_adults }} dewasa + {{ $room->capacity_children }} anak</td><td>Rp {{ number_format($room->offer->price,0,',','.') }}</td><td>{{ $room->total_units }}</td><td><x-status-badge :status='$room->status' /></td><td><a class='btn btn-sm btn-outline-lokantara' href='{{ route('mitra.accommodation.rooms.edit',[$accommodation,$room]) }}'>Edit</a> <a class='btn btn-sm btn-outline-lokantara' href='{{ route('mitra.accommodation.rooms.calendar',[$accommodation,$room]) }}'>Kalender</a></td></tr>@endforeach</tbody>@endif</x-table-wrapper>
<x-content-card title='Riwayat moderasi' class='mt-3'>@forelse($accommodation->moderationReports as $report)@foreach($report->actions as $action)<div class='border-bottom py-2'><strong>{{ str($action->action_type)->headline() }}</strong> · {{ $action->created_at?->format('d M Y H:i') }}<div>{{ $action->notes }}</div></div>@endforeach @empty<x-empty-state title='Belum ada riwayat' description='Riwayat muncul setelah diajukan.' compact />@endforelse</x-content-card>
@endsection
