<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Mitra\AccommodationController;
use App\Http\Controllers\Mitra\BankAccountController;
use App\Http\Controllers\Mitra\CatalogResourceController;
use App\Http\Controllers\Mitra\CulinaryController;
use App\Http\Controllers\Mitra\EventController;
use App\Http\Controllers\Mitra\FeatureRequestController;
use App\Http\Controllers\Mitra\KycController;
use App\Http\Controllers\Mitra\MemberController;
use App\Http\Controllers\Mitra\OrderController;
use App\Http\Controllers\Mitra\ProfileController;
use App\Http\Controllers\Mitra\RentalController;
use App\Http\Controllers\Mitra\TourismController;
use App\Http\Controllers\Mitra\TicketController;
use App\Http\Controllers\Mitra\WithdrawalController;
use App\Http\Controllers\Mitra\VoucherController as MitraVoucherController;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth', 'verified', 'active.user', 'active.mitra', 'permission:access.mitra'])->prefix('mitra')->name('mitra.')->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'mitra'])->name('dashboard');
    Route::get('/{mitra}/dashboard', [DashboardController::class, 'mitra'])->name('context.dashboard');
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::put('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::put('/profile/password', [ProfileController::class, 'updatePassword'])->name('profile.password.update');
    Route::post('/profile/media/{type}', [ProfileController::class, 'media'])->name('profile.media');
    Route::put('/profile/operating-hours', [ProfileController::class, 'hours'])->name('profile.hours');
    Route::get('/kyc', [KycController::class, 'index'])->name('kyc.index');
    Route::post('/kyc', [KycController::class, 'store'])->name('kyc.store');
    Route::get('/kyc/{document}/download', [KycController::class, 'download'])->name('kyc.download');
    Route::get('/members', [MemberController::class, 'index'])->name('members.index');
    Route::post('/members', [MemberController::class, 'store'])->name('members.store');
    Route::post('/members/{member}/reset-password', [MemberController::class, 'resetPassword'])->name('members.reset-password');
    Route::delete('/members/{member}', [MemberController::class, 'destroy'])->name('members.destroy');
    Route::get('/features', [FeatureRequestController::class, 'index'])->name('features.index');
    Route::post('/features/requests', [FeatureRequestController::class, 'store'])->name('features.store');
    Route::get('/bank-accounts', [BankAccountController::class, 'index'])->name('bank-accounts.index');
    Route::post('/bank-accounts', [BankAccountController::class, 'store'])->name('bank-accounts.store');
    Route::delete('/bank-accounts/{account}', [BankAccountController::class, 'destroy'])->name('bank-accounts.destroy');
    Route::get('/tourism', [TourismController::class, 'index'])->name('tourism.index');
    Route::get('/tourism/create', [TourismController::class, 'create'])->name('tourism.create');
    Route::post('/tourism', [TourismController::class, 'store'])->name('tourism.store');
    Route::get('/tourism/{tourism}', [TourismController::class, 'show'])->name('tourism.show');
    Route::get('/tourism/{tourism}/edit', [TourismController::class, 'edit'])->name('tourism.edit');
    Route::put('/tourism/{tourism}', [TourismController::class, 'update'])->name('tourism.update');
    Route::post('/tourism/{tourism}/submit', [TourismController::class, 'submit'])->name('tourism.submit');
    Route::post('/tourism/{tourism}/archive', [TourismController::class, 'archive'])->name('tourism.archive');
    Route::post('/tourism/{tourism}/media', [TourismController::class, 'media'])->name('tourism.media');
    Route::put('/tourism/{tourism}/hours', [TourismController::class, 'hours'])->name('tourism.hours');
    Route::post('/tourism/{tourism}/packages', [TourismController::class, 'package'])->name('tourism.packages.store');
    Route::put('/tourism/{tourism}/packages/{package}', [TourismController::class, 'updatePackage'])->name('tourism.packages.update');
    Route::delete('/tourism/{tourism}/packages/{package}', [TourismController::class, 'destroyPackage'])->name('tourism.packages.destroy');
    Route::put('/tourism/{tourism}/packages/{package}/quota', [TourismController::class, 'quota'])->name('tourism.quota');
    Route::get('/accommodation', [AccommodationController::class, 'index'])->name('accommodation.index');
    Route::get('/accommodation/create', [AccommodationController::class, 'create'])->name('accommodation.create');
    Route::post('/accommodation', [AccommodationController::class, 'store'])->name('accommodation.store');
    Route::get('/accommodation/{accommodation}', [AccommodationController::class, 'show'])->name('accommodation.show');
    Route::get('/accommodation/{accommodation}/edit', [AccommodationController::class, 'edit'])->name('accommodation.edit');
    Route::put('/accommodation/{accommodation}', [AccommodationController::class, 'update'])->name('accommodation.update');
    Route::post('/accommodation/{accommodation}/submit', [AccommodationController::class, 'submit'])->name('accommodation.submit');
    Route::post('/accommodation/{accommodation}/archive', [AccommodationController::class, 'archive'])->name('accommodation.archive');
    Route::post('/accommodation/{accommodation}/media', [AccommodationController::class, 'media'])->name('accommodation.media');
    Route::post('/accommodation/{accommodation}/rooms', [AccommodationController::class, 'storeRoom'])->name('accommodation.rooms.store');
    Route::get('/accommodation/{accommodation}/rooms/{room}/edit', [AccommodationController::class, 'editRoom'])->name('accommodation.rooms.edit');
    Route::put('/accommodation/{accommodation}/rooms/{room}', [AccommodationController::class, 'updateRoom'])->name('accommodation.rooms.update');
    Route::post('/accommodation/{accommodation}/rooms/{room}/archive', [AccommodationController::class, 'archiveRoom'])->name('accommodation.rooms.archive');
    Route::post('/accommodation/{accommodation}/rooms/{room}/media', [AccommodationController::class, 'roomMedia'])->name('accommodation.rooms.media');
    Route::get('/accommodation/{accommodation}/rooms/{room}/calendar', [AccommodationController::class, 'calendar'])->name('accommodation.rooms.calendar');
    Route::put('/accommodation/{accommodation}/rooms/{room}/calendar', [AccommodationController::class, 'updateCalendar'])->name('accommodation.rooms.calendar.update');
    Route::resource('culinary', CulinaryController::class)->except(['destroy']);
    Route::post('/culinary/{culinary}/submit', [CulinaryController::class, 'submit'])->name('culinary.submit');
    Route::post('/culinary/{culinary}/archive', [CulinaryController::class, 'archive'])->name('culinary.archive');
    Route::post('/culinary/{culinary}/menu-categories', [CulinaryController::class, 'category'])->name('culinary.categories.store');
    Route::post('/culinary/{culinary}/menu-categories/{category}/items', [CulinaryController::class, 'item'])->name('culinary.items.store');
    Route::put('/culinary/{culinary}/menu-items/{item}', [CulinaryController::class, 'updateItem'])->name('culinary.items.update');
    Route::delete('/culinary/{culinary}/menu-items/{item}', [CulinaryController::class, 'destroyItem'])->name('culinary.items.destroy');
    Route::put('/culinary/{culinary}/slots', [CulinaryController::class, 'slot'])->name('culinary.slots.update');
    Route::patch('/culinary/{culinary}/reservations/{reservation}', [CulinaryController::class, 'decide'])->name('culinary.reservations.decide');
    Route::resource('event', EventController::class)->except(['destroy']);
    Route::post('/event/{event}/submit', [EventController::class, 'submit'])->name('event.submit');
    Route::post('/event/{event}/archive', [EventController::class, 'archive'])->name('event.archive');
    Route::post('/event/{event}/schedules', [EventController::class, 'schedule'])->name('event.schedules.store');
    Route::post('/event/{event}/ticket-types', [EventController::class, 'ticketType'])->name('event.ticket-types.store');
    Route::put('/event/{event}/ticket-types/{type}', [EventController::class, 'updateTicketType'])->name('event.ticket-types.update');
    Route::delete('/event/{event}/ticket-types/{type}', [EventController::class, 'destroyTicketType'])->name('event.ticket-types.destroy');
    Route::post('/event/{event}/ticket-types/{type}/issue', [EventController::class, 'issue'])->name('event.tickets.issue');
    Route::resource('rental', RentalController::class)->except(['destroy']);
    Route::post('/rental/{rental}/submit', [RentalController::class, 'submit'])->name('rental.submit');
    Route::post('/rental/{rental}/archive', [RentalController::class, 'archive'])->name('rental.archive');
    Route::post('/rental/{rental}/rates', [RentalController::class, 'rate'])->name('rental.rates.store');
    Route::put('/rental/{rental}/rates/{rate}', [RentalController::class, 'updateRate'])->name('rental.rates.update');
    Route::delete('/rental/{rental}/rates/{rate}', [RentalController::class, 'destroyRate'])->name('rental.rates.destroy');
    Route::put('/rental/{rental}/availability', [RentalController::class, 'availability'])->name('rental.availability.update');
    Route::patch('/rental/{rental}/bookings/{booking}', [RentalController::class, 'transition'])->name('rental.bookings.transition');
    Route::patch('/renter-documents/{document}', [RentalController::class, 'reviewDocument'])->name('renter-documents.review');
    Route::post('/catalog/{domain}/{entity}/media', [CatalogResourceController::class, 'media'])->name('catalog.media');
    Route::put('/catalog/{domain}/{entity}/hours', [CatalogResourceController::class, 'hours'])->name('catalog.hours');
    Route::put('/catalog/{domain}/{entity}/reviews/{review}/reply', [CatalogResourceController::class, 'reply'])->name('catalog.reviews.reply');
    Route::post('/catalog/{domain}/{entity}/virtual-tour/upload', [\App\Http\Controllers\Mitra\VirtualTourController::class, 'upload'])->name('catalog.virtual-tour.upload');
    Route::delete('/catalog/{domain}/{entity}/virtual-tour', [\App\Http\Controllers\Mitra\VirtualTourController::class, 'destroy'])->name('catalog.virtual-tour.destroy');
    Route::get('/vouchers', [MitraVoucherController::class, 'index'])->name('vouchers.index');
    Route::get('/vouchers/create', [MitraVoucherController::class, 'create'])->name('vouchers.create');
    Route::post('/vouchers', [MitraVoucherController::class, 'store'])->name('vouchers.store');
    Route::get('/orders', [OrderController::class, 'index'])->name('orders.index');
    Route::get('/orders/{order}', [OrderController::class, 'show'])->name('orders.show');
    Route::patch('/tickets/{ticket}/revoke', [TicketController::class, 'revoke'])->name('tickets.revoke');
    Route::get('/withdrawals', [WithdrawalController::class, 'index'])->name('withdrawals.index');
    Route::get('/withdrawals/create', [WithdrawalController::class, 'create'])->name('withdrawals.create');
    Route::post('/withdrawals', [WithdrawalController::class, 'store'])->name('withdrawals.store');
    Route::get('/withdrawals/{withdrawal}', [WithdrawalController::class, 'show'])->name('withdrawals.show');
    Route::patch('/withdrawals/{withdrawal}/cancel', [WithdrawalController::class, 'cancel'])->name('withdrawals.cancel');
});
