<?php
namespace App\Http\Controllers\Mitra;
use App\Actions\Catalog\SubmitCatalogDomain;use App\Actions\Culinary\DecideCulinaryReservation;use App\Actions\Culinary\SaveCulinaryVenue;use App\Http\Controllers\Controller;use App\Http\Controllers\Mitra\Concerns\ResolvesActiveMitra;use App\Http\Requests\Mitra\SaveCulinaryVenueRequest;use App\Models\CatalogEntity;use App\Models\Category;use App\Models\CulinaryMenuCategory;use App\Models\CulinaryMenuItem;use App\Models\CulinaryReservation;use App\Models\CulinaryTableSlot;use App\Models\Facility;use App\Models\Region;use App\Models\ServiceType;use App\Services\AuditLogger;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\View\View;
class CulinaryController extends Controller
{use ResolvesActiveMitra;public function index(Request $r):View{abort_unless($r->user()->can('culinary.manage'),403);$items=CatalogEntity::where('mitra_id',$this->activeMitra($r)->id)->whereHas('serviceType',fn($q)=>$q->where('code','culinary'))->latest()->paginate(15);return view('mitra.catalog-domain.index',['items'=>$items,'title'=>'Kuliner','routePrefix'=>'mitra.culinary']);}public function create(Request $r):View{abort_unless($r->user()->can('culinary.manage'),403);return view('mitra.catalog-domain.form',$this->refs()+['title'=>'Kuliner','routePrefix'=>'mitra.culinary','domain'=>'culinary']);}public function store(SaveCulinaryVenueRequest $r,SaveCulinaryVenue $a):RedirectResponse{$e=$a->execute($this->activeMitra($r),$r->validated(),$r->user());return redirect()->route('mitra.culinary.show',$e);}    public function show(Request $r, CatalogEntity $culinary): View
    {
        $this->owned($r, $culinary);
        return view('mitra.catalog-domain.show', [
            'item' => $culinary->load(['culinary.menuCategories.items', 'culinary.tableSlots.reservations', 'location', 'media', 'facilities', 'moderationReports.actions']),
            'title' => 'Kuliner',
            'routePrefix' => 'mitra.culinary',
            'domain' => 'culinary'
        ]);
    }

    public function edit(Request $r, CatalogEntity $culinary): View
    {
        $this->owned($r, $culinary);
        return view('mitra.catalog-domain.form', $this->refs() + [
            'item' => $culinary->load(['culinary', 'location']),
            'title' => 'Kuliner',
            'routePrefix' => 'mitra.culinary',
            'domain' => 'culinary'
        ]);
    }public function update(SaveCulinaryVenueRequest $r,CatalogEntity $culinary,SaveCulinaryVenue $a):RedirectResponse{$this->owned($r,$culinary);$a->execute($this->activeMitra($r),$r->validated(),$r->user(),$culinary);return redirect()->route('mitra.culinary.show',$culinary);}public function submit(Request $r,CatalogEntity $culinary,SubmitCatalogDomain $a):RedirectResponse{$this->owned($r,$culinary);$a->execute($culinary,'culinary',$r->user(),[$culinary->culinary->menuItems()->where('status','active')->exists()=>'menu aktif']);return back();}public function archive(Request $r,CatalogEntity $culinary,AuditLogger $audit):RedirectResponse{$this->owned($r,$culinary);abort_unless(in_array($culinary->status,['draft','rejected','published'],true),422);$before=$culinary->status;$culinary->update(['status'=>'archived','archived_at'=>now()]);$audit->record('culinary.archived',$culinary,['status'=>$before],['status'=>'archived'],$r->user());return redirect()->route('mitra.culinary.index')->with('status','Kuliner diarsipkan.');}
public function category(Request $r,CatalogEntity $culinary):RedirectResponse{$this->owned($r,$culinary);$d=$r->validate(['name'=>'required|string|max:150','sort_order'=>'nullable|integer|min:0']);$culinary->culinary->menuCategories()->create($d);return back();}public function item(Request $r,CatalogEntity $culinary,CulinaryMenuCategory $category):RedirectResponse{$this->owned($r,$culinary);abort_unless($category->culinary_venue_id===$culinary->culinary->id,404);$d=$r->validate(['name'=>'required|string|max:150','description'=>'nullable|string','price'=>'required|numeric|min:0','is_featured'=>'sometimes|boolean']);$category->items()->create($d+['culinary_venue_id'=>$culinary->culinary->id,'status'=>'active']);return back();}public function slot(Request $r,CatalogEntity $culinary):RedirectResponse{$this->owned($r,$culinary);$d=$r->validate(['service_date'=>'required|date|after_or_equal:today','starts_at'=>'required|date_format:H:i','ends_at'=>'required|date_format:H:i|after:starts_at','capacity_tables'=>'required|integer|min:1','capacity_guests'=>'required|integer|min:1']);$culinary->culinary->tableSlots()->updateOrCreate(['service_date'=>$d['service_date'],'starts_at'=>$d['starts_at']],$d+['status'=>'available']);return back();}public function decide(Request $r,CatalogEntity $culinary,CulinaryReservation $reservation,DecideCulinaryReservation $a):RedirectResponse{$this->owned($r,$culinary);abort_unless($reservation->culinary_venue_id===$culinary->culinary->id,404);$d=$r->validate(['decision'=>'required|in:confirm,reject','reason'=>'nullable|required_if:decision,reject|string']);$a->execute($reservation,$d['decision'],$r->user(),$d['reason']??null);return back();}private function owned(Request $r,CatalogEntity $e):void{abort_unless($r->user()->can('culinary.manage')&&$e->mitra_id===$this->activeMitra($r)->id&&$e->serviceType()->where('code','culinary')->exists(),403);}private function refs():array{$id=ServiceType::where('code','culinary')->value('id');return ['categories'=>Category::where('service_type_id',$id)->get(),'facilities'=>Facility::where('service_type_id',$id)->get(),'regions'=>Region::orderBy('name')->get()];}}
