@extends('layouts.mitra')
@section('title',$tourism->name) @section('page-title',$tourism->name) @section('page-description','Preview dan pengelolaan seluruh data destinasi.')
@section('content')
<div class='d-flex gap-2 mb-3'><x-status-badge :status='$tourism->status' /><a class='btn btn-sm btn-outline-lokantara' href='{{ route('mitra.tourism.edit',$tourism) }}'>Edit</a>@if(in_array($tourism->status,['draft','rejected']))<form method='POST' action='{{ route('mitra.tourism.submit',$tourism) }}'>@csrf<button class='btn btn-sm btn-lokantara'>Ajukan moderasi</button></form>@endif @if(in_array($tourism->status,['draft','rejected','published']))<form method='POST' action='{{ route('mitra.tourism.archive',$tourism) }}'>@csrf<button class='btn btn-sm btn-outline-danger'>Arsipkan</button></form>@endif</div>
<div class='row g-3'><div class='col-lg-7'><x-content-card title='Preview'><h2>{{ $tourism->name }}</h2><p>{{ $tourism->description ?: 'Deskripsi belum diisi.' }}</p><p>{{ $tourism->address }}</p><p>Koordinat: {{ $tourism->location?->latitude }}, {{ $tourism->location?->longitude }}</p><div class='d-flex gap-2 flex-wrap'>@foreach($tourism->facilities as $facility)<span class='badge text-bg-light'>{{ $facility->name }}</span>@endforeach</div></x-content-card></div>
<div class='col-lg-5'><x-content-card title='Media'><form method='POST' enctype='multipart/form-data' action='{{ route('mitra.tourism.media',$tourism) }}'>@csrf<input class='form-control mb-2' type='file' name='image' accept='image/jpeg,image/png,image/webp' required><select class='form-select mb-2' name='role'><option value='cover'>Cover</option><option value='gallery'>Galeri</option></select><button class='btn btn-sm btn-lokantara'>Unggah</button></form><p class='mt-3 mb-0'>{{ $tourism->media->count() }} media tersimpan.</p></x-content-card></div></div>
<div class='row g-3 mt-1'><div class='col-lg-6'><x-content-card title='Jam operasional'><form method='POST' action='{{ route('mitra.tourism.hours',$tourism) }}'>@csrf @method('PUT')@for($day=1;$day<=7;$day++)<div class='row align-items-end mb-2'><input type='hidden' name='hours[{{ $day }}][weekday]' value='{{ $day }}'><div class='col-2'>Hari {{ $day }}</div><div class='col'><input class='form-control' type='time' name='hours[{{ $day }}][opens_at]' value='09:00'></div><div class='col'><input class='form-control' type='time' name='hours[{{ $day }}][closes_at]' value='17:00'></div></div>@endfor<button class='btn btn-sm btn-lokantara'>Simpan jam</button></form></x-content-card></div>
<div class='col-lg-6'><x-content-card title='Paket tiket'><form method='POST' action='{{ route('mitra.tourism.packages.store',$tourism) }}'>@csrf<div class='row'><div class='col'><input class='form-control' name='name' placeholder='Nama paket' required></div><div class='col'><input class='form-control' name='price' type='number' step='0.01' placeholder='Harga' required></div><div class='col'><input class='form-control' name='quota_per_day' type='number' placeholder='Kuota/hari'></div></div><button class='btn btn-sm btn-lokantara mt-2'>Tambah</button></form>@foreach($tourism->offers as $offer)<hr><strong>{{ $offer->name }}</strong> — Rp {{ number_format($offer->price,0,',','.') }}<form class='row mt-2' method='POST' action='{{ route('mitra.tourism.quota',[$tourism,$offer->ticketPackage]) }}'>@csrf @method('PUT')<div class='col'><input class='form-control' type='date' name='service_date' required></div><div class='col'><input class='form-control' type='number' name='capacity' placeholder='Kuota' required></div><div class='col'><button class='btn btn-sm btn-outline-lokantara'>Simpan kuota</button></div></form>@endforeach</x-content-card></div></div>
<x-content-card title='Riwayat moderasi' class='mt-3'>@forelse($tourism->moderationReports as $report)@foreach($report->actions as $action)<div class='border-bottom py-2'><strong>{{ str($action->action_type)->headline() }}</strong> · {{ $action->created_at?->format('d M Y H:i') }}<div>{{ $action->notes }}</div></div>@endforeach @empty<x-empty-state title='Belum ada riwayat' description='Riwayat muncul setelah konten diajukan.' compact />@endforelse</x-content-card>
@endsection
