<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('event_ticket_types', function (Blueprint $table) { $table->unsignedInteger('reserved_quantity')->default(0)->after('issued_quantity'); });
        try { DB::statement('ALTER TABLE event_ticket_types DROP CONSTRAINT event_ticket_types_quota_check'); } catch (\Throwable) { try { DB::statement('ALTER TABLE event_ticket_types DROP CHECK event_ticket_types_quota_check'); } catch (\Throwable) {} }
        DB::statement('ALTER TABLE event_ticket_types ADD CONSTRAINT event_ticket_types_quota_check CHECK (quota > 0 AND issued_quantity + reserved_quantity <= quota)');

        Schema::create('vouchers', function (Blueprint $table) {
            $table->ulid('id')->primary();$table->foreignUlid('mitra_id')->nullable()->constrained()->restrictOnDelete();$table->string('code',64);$table->string('name',191);$table->string('discount_type',32);$table->decimal('flat_amount',15,2)->nullable();$table->unsignedSmallInteger('percentage_basis_points')->nullable();$table->decimal('maximum_discount_amount',15,2)->nullable();$table->decimal('minimum_order_amount',15,2)->default(0);$table->unsignedInteger('usage_limit')->nullable();$table->unsignedInteger('used_count')->default(0);$table->unsignedInteger('per_user_limit')->default(1);$table->timestamp('starts_at')->nullable();$table->timestamp('ends_at')->nullable();$table->string('status',32)->default('draft');$table->foreignUlid('created_by')->constrained('users')->restrictOnDelete();$table->timestamps();$table->softDeletes();$table->string('scope_key',26)->storedAs("COALESCE(mitra_id, 'PLATFORM')");$table->unique(['scope_key','code'],'vouchers_scope_code_unique');$table->index(['status','starts_at','ends_at']);
        });
        DB::statement("ALTER TABLE vouchers ADD CONSTRAINT vouchers_discount_check CHECK ((discount_type = 'flat' AND flat_amount IS NOT NULL AND flat_amount > 0 AND percentage_basis_points IS NULL) OR (discount_type = 'percentage' AND percentage_basis_points BETWEEN 1 AND 10000 AND flat_amount IS NULL))");
        DB::statement('ALTER TABLE vouchers ADD CONSTRAINT vouchers_limit_check CHECK (used_count <= usage_limit OR usage_limit IS NULL)');
        Schema::create('voucher_service_types', function (Blueprint $table) {$table->foreignUlid('voucher_id')->constrained()->cascadeOnDelete();$table->foreignId('service_type_id')->constrained()->restrictOnDelete();$table->primary(['voucher_id','service_type_id']);});
        Schema::create('voucher_claims', function (Blueprint $table) {$table->ulid('id')->primary();$table->foreignUlid('voucher_id')->constrained()->restrictOnDelete();$table->foreignUlid('user_id')->constrained()->restrictOnDelete();$table->string('status',32)->default('claimed');$table->timestamp('claimed_at')->nullable();$table->timestamp('expires_at')->nullable();$table->timestamps();$table->unique(['voucher_id','user_id']);});

        Schema::create('orders', function (Blueprint $table) {
            $table->ulid('id')->primary();$table->string('order_number',32)->unique();$table->foreignUlid('user_id')->constrained()->restrictOnDelete();$table->foreignUlid('mitra_id')->constrained()->restrictOnDelete();$table->foreignUlid('voucher_id')->nullable()->constrained()->restrictOnDelete();$table->char('currency',3)->default('IDR');$table->decimal('subtotal',15,2);$table->decimal('admin_fee',15,2)->default(0);$table->decimal('discount_amount',15,2)->default(0);$table->decimal('total_amount',15,2);$table->unsignedSmallInteger('commission_basis_points')->default(0);$table->decimal('commission_amount',15,2)->default(0);$table->decimal('mitra_net_amount',15,2)->default(0);$table->string('status',32)->default('pending_payment');$table->string('payment_status',32)->default('pending');$table->json('user_snapshot');$table->json('mitra_snapshot');$table->json('voucher_snapshot')->nullable();$table->timestamp('placed_at')->nullable();$table->timestamp('expires_at')->nullable();$table->timestamp('paid_at')->nullable();$table->timestamp('cancelled_at')->nullable();$table->timestamps();$table->index(['user_id','status','created_at']);$table->index(['mitra_id','status','created_at']);
        });
        DB::statement('ALTER TABLE orders ADD CONSTRAINT orders_money_check CHECK (subtotal >= 0 AND admin_fee >= 0 AND discount_amount >= 0 AND total_amount >= 0 AND commission_amount >= 0 AND mitra_net_amount >= 0)');
        Schema::create('order_items', function (Blueprint $table) {
            $table->ulid('id')->primary();$table->foreignUlid('order_id')->constrained()->restrictOnDelete();$table->foreignUlid('mitra_id')->constrained()->restrictOnDelete();$table->foreignUlid('catalog_offer_id')->constrained()->restrictOnDelete();$table->string('resource_type',64);$table->ulid('reference_id');$table->unsignedInteger('quantity');$table->string('item_name',191);$table->string('sku',100)->nullable();$table->decimal('unit_price',15,2);$table->decimal('subtotal',15,2);$table->decimal('admin_fee',15,2)->default(0);$table->decimal('discount_amount',15,2)->default(0);$table->decimal('line_total',15,2);$table->date('booking_date')->nullable();$table->timestamp('starts_at')->nullable();$table->timestamp('ends_at')->nullable();$table->string('fulfillment_status',32)->default('reserved');$table->json('details')->nullable();$table->timestamps();$table->index('order_id');$table->index(['catalog_offer_id','booking_date']);$table->index(['resource_type','reference_id'],'order_items_resource_idx');
        });
        DB::statement('ALTER TABLE order_items ADD CONSTRAINT order_items_money_check CHECK (quantity > 0 AND unit_price >= 0 AND subtotal >= 0 AND line_total >= 0)');
        Schema::create('idempotency_keys', function (Blueprint $table) {$table->ulid('id')->primary();$table->foreignUlid('user_id')->constrained()->cascadeOnDelete();$table->string('scope',64);$table->string('key_value',191);$table->char('fingerprint',64);$table->foreignUlid('order_id')->nullable()->constrained()->nullOnDelete();$table->unsignedSmallInteger('response_status')->nullable();$table->json('response_payload')->nullable();$table->timestamp('expires_at')->nullable();$table->timestamp('created_at')->useCurrent();$table->unique(['user_id','scope','key_value'],'idempotency_user_scope_key_unique');});
        Schema::create('payments', function (Blueprint $table) {$table->ulid('id')->primary();$table->foreignUlid('order_id')->constrained()->restrictOnDelete();$table->foreignUlid('mitra_id')->constrained()->restrictOnDelete();$table->string('provider',32)->default('pending_gateway');$table->string('provider_reference',191)->nullable();$table->string('method',32)->nullable();$table->char('currency',3)->default('IDR');$table->decimal('amount',15,2);$table->string('status',32)->default('pending');$table->timestamp('paid_at')->nullable();$table->timestamp('expired_at')->nullable();$table->timestamp('failed_at')->nullable();$table->string('failure_code',100)->nullable();$table->json('provider_snapshot')->nullable();$table->timestamps();$table->unique(['provider','provider_reference']);$table->index(['order_id','status']);$table->index(['mitra_id','status','created_at']);});
        Schema::create('voucher_usages', function (Blueprint $table) {$table->ulid('id')->primary();$table->foreignUlid('voucher_id')->constrained()->restrictOnDelete();$table->foreignUlid('voucher_claim_id')->nullable()->constrained()->restrictOnDelete();$table->foreignUlid('order_id')->constrained()->restrictOnDelete();$table->foreignUlid('user_id')->constrained()->restrictOnDelete();$table->decimal('discount_amount',15,2);$table->string('status',32)->default('applied');$table->timestamp('applied_at')->nullable();$table->timestamp('reversed_at')->nullable();$table->timestamp('created_at')->useCurrent();$table->unique(['voucher_id','order_id']);$table->index(['voucher_id','user_id','status']);});
        Schema::create('order_reservation_holds', function (Blueprint $table) {$table->ulid('id')->primary();$table->foreignUlid('order_item_id')->constrained()->restrictOnDelete();$table->string('resource_type',64);$table->ulid('resource_id');$table->date('service_date')->nullable();$table->unsignedInteger('quantity');$table->string('status',32)->default('active');$table->json('details')->nullable();$table->timestamps();$table->index(['resource_type','resource_id','status'],'order_holds_resource_status_idx');});
        Schema::create('tickets', function (Blueprint $table) {$table->ulid('id')->primary();$table->string('ticket_code',32)->unique();$table->foreignUlid('order_item_id')->constrained()->restrictOnDelete();$table->foreignUlid('mitra_id')->constrained()->restrictOnDelete();$table->foreignUlid('holder_user_id')->nullable()->constrained('users')->restrictOnDelete();$table->char('qr_token_hash',64)->unique();$table->string('status',32)->default('active');$table->timestamp('valid_from')->nullable();$table->timestamp('valid_until')->nullable();$table->timestamp('used_at')->nullable();$table->timestamps();$table->index(['mitra_id','status','valid_until']);});

        Schema::create('ledger_accounts', function (Blueprint $table) {$table->ulid('id')->primary();$table->foreignUlid('mitra_id')->nullable()->constrained()->restrictOnDelete();$table->foreignUlid('user_id')->nullable()->constrained()->restrictOnDelete();$table->string('system_code',64)->nullable();$table->string('account_type',32);$table->char('currency',3)->default('IDR');$table->string('status',32)->default('active');$table->timestamps();$table->unique(['mitra_id','account_type','currency']);$table->unique(['user_id','account_type','currency']);$table->unique(['system_code','currency']);});
        DB::statement('ALTER TABLE ledger_accounts ADD CONSTRAINT ledger_accounts_owner_check CHECK ((mitra_id IS NOT NULL) + (user_id IS NOT NULL) + (system_code IS NOT NULL) = 1)');
        Schema::create('ledger_journals', function (Blueprint $table) {$table->ulid('id')->primary();$table->string('journal_number',32)->unique();$table->foreignUlid('mitra_id')->nullable()->constrained()->restrictOnDelete();$table->string('event_key',191)->unique();$table->string('event_type',64);$table->foreignUlid('order_id')->nullable()->constrained()->restrictOnDelete();$table->foreignUlid('payment_id')->nullable()->constrained()->restrictOnDelete();$table->foreignUlid('reversal_of_id')->nullable()->constrained('ledger_journals')->restrictOnDelete();$table->string('description',500);$table->timestamp('effective_at')->nullable();$table->timestamp('posted_at')->nullable();$table->json('metadata')->nullable();$table->timestamp('created_at')->useCurrent();$table->index(['mitra_id','effective_at']);});
        Schema::create('ledger_lines', function (Blueprint $table) {$table->ulid('id')->primary();$table->foreignUlid('ledger_journal_id')->constrained()->restrictOnDelete();$table->foreignUlid('ledger_account_id')->constrained()->restrictOnDelete();$table->unsignedSmallInteger('sequence');$table->decimal('debit_amount',15,2)->default(0);$table->decimal('credit_amount',15,2)->default(0);$table->char('currency',3)->default('IDR');$table->timestamp('created_at')->useCurrent();$table->unique(['ledger_journal_id','sequence']);$table->index(['ledger_account_id','created_at']);});
        DB::statement('ALTER TABLE ledger_lines ADD CONSTRAINT ledger_lines_side_check CHECK ((debit_amount > 0 AND credit_amount = 0) OR (credit_amount > 0 AND debit_amount = 0))');
        Schema::create('mitra_balances', function (Blueprint $table) {$table->foreignUlid('mitra_id')->primary()->constrained()->restrictOnDelete();$table->char('currency',3)->default('IDR');$table->decimal('available_amount',15,2)->default(0);$table->decimal('held_amount',15,2)->default(0);$table->decimal('total_earned_amount',15,2)->default(0);$table->foreignUlid('last_journal_id')->nullable()->constrained('ledger_journals')->restrictOnDelete();$table->timestamp('rebuilt_at')->nullable();$table->timestamp('updated_at')->nullable();});
        Schema::table('reviews', function (Blueprint $table) {$table->foreign('order_item_id')->references('id')->on('order_items')->restrictOnDelete();});
    }

    public function down(): void
    {
        Schema::table('reviews', function (Blueprint $table) {$table->dropForeign(['order_item_id']);});
        foreach (['mitra_balances','ledger_lines','ledger_journals','ledger_accounts','tickets','order_reservation_holds','voucher_usages','payments','idempotency_keys','order_items','orders','voucher_claims','voucher_service_types','vouchers'] as $table) Schema::dropIfExists($table);
        try { DB::statement('ALTER TABLE event_ticket_types DROP CONSTRAINT event_ticket_types_quota_check'); } catch (\Throwable) { try { DB::statement('ALTER TABLE event_ticket_types DROP CHECK event_ticket_types_quota_check'); } catch (\Throwable) {} }
        Schema::table('event_ticket_types', function (Blueprint $table) {$table->dropColumn('reserved_quantity');});
        DB::statement('ALTER TABLE event_ticket_types ADD CONSTRAINT event_ticket_types_quota_check CHECK (quota > 0 AND issued_quantity <= quota)');
    }
};
