<?php

return [
    'consumer' => [
        ['label' => 'Dashboard', 'route' => 'consumer.dashboard', 'permission' => 'access.consumer'],
        ['label' => 'Notifikasi', 'href' => '#notifications', 'permission' => 'notifications.view'],
    ],
    'mitra' => [
        ['label' => 'Dashboard', 'route' => 'mitra.dashboard', 'permission' => 'access.mitra'],
        ['label' => 'Wisata', 'route' => 'mitra.tourism.index', 'permission' => 'tourism.manage'],
        ['label' => 'Penginapan', 'route' => 'mitra.accommodation.index', 'permission' => 'accommodation.manage'],
        ['label' => 'Kuliner', 'route' => 'mitra.culinary.index', 'permission' => 'culinary.manage'],
        ['label' => 'Event', 'route' => 'mitra.event.index', 'permission' => 'event.manage'],
        ['label' => 'Rental', 'route' => 'mitra.rental.index', 'permission' => 'rental.manage'],
        ['label' => 'Pesanan', 'route' => 'mitra.orders.index', 'permission' => 'orders.view'],
        ['label' => 'Voucher', 'route' => 'mitra.vouchers.index', 'permission' => 'vouchers.manage'],
        ['label' => 'Penarikan Dana', 'route' => 'mitra.withdrawals.index', 'permission' => 'withdrawals.view'],
        ['label' => 'Profil Mitra', 'route' => 'mitra.profile.edit', 'permission' => 'mitras.view'],
        ['label' => 'Anggota Tim', 'route' => 'mitra.members.index', 'permission' => 'members.manage'],
        ['label' => 'Dokumen KYC', 'route' => 'mitra.kyc.index', 'permission' => 'kyc.submit'],
        ['label' => 'Fitur Layanan', 'route' => 'mitra.features.index', 'permission' => 'mitras.update'],
        ['label' => 'Rekening Bank', 'route' => 'mitra.bank-accounts.index', 'permission' => 'bank-accounts.manage'],
    ],
    'gatekeeper' => [
        ['label' => 'Dashboard', 'route' => 'gatekeeper.dashboard', 'permission' => 'access.gatekeeper'],
        ['label' => 'Validasi Tiket QR', 'route' => 'gatekeeper.event-tickets.index', 'permission' => 'tickets.validate'],
    ],
    'admin' => [
        ['label' => 'Dashboard', 'route' => 'admin.dashboard', 'permission' => 'access.admin'],
        ['label' => 'Pengguna', 'route' => 'admin.users.index', 'permission' => 'users.manage'],
        ['label' => 'Kelola Mitra', 'route' => 'admin.mitras.index', 'permission' => 'mitras.create'],
        ['label' => 'Moderasi Wisata', 'route' => 'admin.tourism.index', 'permission' => 'tourism.moderate'],
        ['label' => 'Moderasi Penginapan', 'route' => 'admin.accommodation.index', 'permission' => 'accommodation.moderate'],
        ['label' => 'Moderasi Kuliner', 'route' => 'admin.culinary.index', 'permission' => 'culinary.moderate'],
        ['label' => 'Moderasi Event', 'route' => 'admin.event.index', 'permission' => 'event.moderate'],
        ['label' => 'Moderasi Rental', 'route' => 'admin.rental.index', 'permission' => 'rental.moderate'],
        ['label' => 'Review KYC', 'route' => 'admin.kyc.index', 'permission' => 'kyc.review'],
        ['label' => 'Request Fitur', 'route' => 'admin.features.index', 'permission' => 'feature-requests.review'],
        ['label' => 'Voucher Platform', 'route' => 'admin.vouchers.index', 'permission' => 'vouchers.manage'],
        ['label' => 'Penarikan Dana', 'route' => 'admin.withdrawals.index', 'permission' => 'withdrawals.process'],
        ['label' => 'Audit Log', 'route' => 'admin.audit.index', 'permission' => 'audit.view'],
    ],
    'super-admin' => [
        ['label' => 'Dashboard', 'route' => 'super-admin.dashboard', 'permission' => 'access.super-admin'],
        ['label' => 'Role System', 'route' => 'super-admin.roles.index', 'permission' => 'roles.manage'],
        ['label' => 'Permission Matrix', 'route' => 'super-admin.permissions.index', 'permission' => 'permissions.manage'],
        ['label' => 'Feature Flags', 'route' => 'super-admin.flags.index', 'permission' => 'feature-flags.manage'],
        ['label' => 'Pengaturan Platform', 'route' => 'super-admin.settings.index', 'permission' => 'settings.manage'],
    ],
];
