@extends('layouts.public')
@section('title',$item->name.' — Lokantara') @section('meta-description',str($item->description)->limit(155))
@section('content')
<section class="public-section"><div class="container public-container"><a href="{{ route($routePrefix.'.index') }}">← Kembali ke {{ strtolower($title) }}</a><div class="section-heading mt-3"><div><p class="public-eyebrow">{{ $title }}</p><h1>{{ $item->name }}</h1><p>{{ $item->address }}</p></div><x-status-badge status="published" /></div><div class="content-card mb-4"><p>{{ $item->description }}</p></div>
@if($routePrefix==='culinary')<div class="content-card"><h2>Menu</h2>@forelse($item->culinary->menuCategories as $category)<h3>{{ $category->name }}</h3><ul>@foreach($category->items->where('status','active') as $menu)<li>{{ $menu->name }} — Rp {{ number_format($menu->price,0,',','.') }} @if($menu->is_featured)<span class="badge text-bg-warning">Unggulan</span>@endif</li>@endforeach</ul>@empty<x-empty-state title="Menu belum tersedia" compact />@endforelse</div>@endif
@if($routePrefix==='event')<div class="content-card"><h2>Jadwal</h2>@forelse($item->event->schedules as $schedule)<p><strong>{{ $schedule->title }}</strong> · {{ $schedule->starts_at->format('d M Y H:i') }}</p>@empty<x-empty-state title="Jadwal belum tersedia" compact />@endforelse<h2>Tiket</h2>@foreach($item->event->ticketTypes as $type)<p>{{ $type->name }} — Rp {{ number_format($type->offer->price,0,',','.') }} · sisa {{ max(0,$type->quota-$type->issued_quantity) }}</p>@endforeach</div>@endif
@if($routePrefix==='rental')<div class="content-card"><h2>Tarif</h2>@foreach($item->rentalVehicle->rates as $rate)<p>{{ str($rate->drive_mode)->headline() }} — Rp {{ number_format($rate->offer->price,0,',','.') }}/{{ $rate->duration_value }} {{ $rate->duration_unit }}</p>@endforeach<p>Deposit: Rp {{ number_format($item->rentalVehicle->deposit_amount,0,',','.') }}</p></div>@endif
<div class="content-card mt-4"><h2>Ulasan</h2>@forelse($item->reviews as $review)<article class="mb-3"><strong>{{ $review->rating }}/5</strong><p>{{ $review->body }}</p>@if($review->reply)<blockquote>{{ $review->reply->body }}</blockquote>@endif</article>@empty<x-empty-state title="Belum ada ulasan published" compact />@endforelse</div></div></section>
@endsection
