<?php
namespace App\Http\Controllers\Public;
use App\Actions\Culinary\CreateCulinaryReservation; use App\Http\Controllers\Controller; use App\Http\Controllers\Public\Concerns\HandlesCatalogInteractions; use App\Http\Requests\Consumer\CreateCulinaryReservationRequest; use App\Models\CatalogEntity; use App\Models\CulinaryTableSlot; use App\Models\FeatureFlag; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\View\View;
class CulinaryController extends Controller
{
    use HandlesCatalogInteractions;
    private function enabled():void{abort_unless(FeatureFlag::where('key_name','public-culinary')->where('status','enabled')->exists(),404);}
    public function index(Request $request):View{$this->enabled();$items=CatalogEntity::publicDomain('culinary')->with(['culinary.menuCategories.items','media','location','region','category','mitra'])->when($request->q,fn($q,$v)=>$q->where(fn($x)=>$x->where('name','like','%'.$v.'%')->orWhere('description','like','%'.$v.'%')))->when($request->category,fn($q,$v)=>$q->whereHas('category',fn($x)=>$x->where('slug',$v)))->paginate(12)->withQueryString();return view('public.catalog-domain.index',['items'=>$items,'title'=>'Kuliner','routePrefix'=>'culinary']);}
    public function show(string $slug):View{$this->enabled();$item=CatalogEntity::publicDomain('culinary')->where('slug',$slug)->with(['culinary.menuCategories.items','culinary.tableSlots'=>fn($q)=>$q->whereDate('service_date','>=',today())->where('status','available')->orderBy('service_date'),'media','facilities','operatingHours','reviews'=>fn($q)=>$q->where('status','published')->with(['user', 'replies.author', 'replies.mitra'])->latest()])->firstOrFail();return view('public.catalog-domain.show',['item'=>$item,'title'=>'Kuliner','routePrefix'=>'culinary']);}
    public function favorite(Request $r,string $slug):RedirectResponse{return $this->toggleFavorite($r,CatalogEntity::publicDomain('culinary')->where('slug',$slug)->firstOrFail(),true);}public function unfavorite(Request $r,string $slug):RedirectResponse{return $this->toggleFavorite($r,CatalogEntity::publicDomain('culinary')->where('slug',$slug)->firstOrFail(),false);}public function review(Request $r,string $slug):RedirectResponse{return $this->storeReview($r,CatalogEntity::publicDomain('culinary')->where('slug',$slug)->firstOrFail());}
    public function reserve(CreateCulinaryReservationRequest $r,string $slug,CulinaryTableSlot $slot,CreateCulinaryReservation $action):RedirectResponse{$entity=CatalogEntity::publicDomain('culinary')->where('slug',$slug)->firstOrFail();abort_unless($entity->culinary->accepts_reservations&&$slot->culinary_venue_id===$entity->culinary->id,404);$action->execute($slot,$r->user(),$r->validated());return back()->with('status','Reservasi dikirim.');}
}
